//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BANKSEntities : DbContext
    {
        public BANKSEntities()
            : base("name=BANKSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Form101Indicators> t_Form101Indicators { get; set; }
        public virtual DbSet<t_BIC_CO> t_BIC_CO { get; set; }
        public virtual DbSet<t_application_F101_actives> t_application_F101_actives { get; set; }
        public virtual DbSet<t_application_F101_passives> t_application_F101_passives { get; set; }
        public virtual DbSet<t_application_F101_actives_top_n> t_application_F101_actives_top_n { get; set; }
        public virtual DbSet<t_application_F101_passives_top_n> t_application_F101_passives_top_n { get; set; }
        public virtual DbSet<t_Form102Indicators_flat> t_Form102Indicators_flat { get; set; }
    
        [DbFunction("BANKSEntities", "f_Form101Indicators_IndCode")]
        public virtual IQueryable<f_Form101Indicators_IndCode_Result> f_Form101Indicators_IndCode(string indCode)
        {
            var indCodeParameter = indCode != null ?
                new ObjectParameter("IndCode", indCode) :
                new ObjectParameter("IndCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_Form101Indicators_IndCode_Result>("[BANKSEntities].[f_Form101Indicators_IndCode](@IndCode)", indCodeParameter);
        }
    
        public virtual int f_p_Data101FullV2(Nullable<int> credorgNumber, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var credorgNumberParameter = credorgNumber.HasValue ?
                new ObjectParameter("CredorgNumber", credorgNumber) :
                new ObjectParameter("CredorgNumber", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_p_Data101FullV2", credorgNumberParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual int f_p_Data101FullV2_(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_p_Data101FullV2_", dateFromParameter, dateToParameter);
        }
    
        public virtual int f_p_Data101FullV2_cursor_by_RegNumber(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_p_Data101FullV2_cursor_by_RegNumber", dateFromParameter, dateToParameter);
        }
    
        [DbFunction("BANKSEntities", "GetHtml")]
        public virtual IQueryable<GetHtml_Result> GetHtml(string resourceEncoding, string baseUrl, string resource)
        {
            var resourceEncodingParameter = resourceEncoding != null ?
                new ObjectParameter("ResourceEncoding", resourceEncoding) :
                new ObjectParameter("ResourceEncoding", typeof(string));
    
            var baseUrlParameter = baseUrl != null ?
                new ObjectParameter("BaseUrl", baseUrl) :
                new ObjectParameter("BaseUrl", typeof(string));
    
            var resourceParameter = resource != null ?
                new ObjectParameter("Resource", resource) :
                new ObjectParameter("Resource", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetHtml_Result>("[BANKSEntities].[GetHtml](@ResourceEncoding, @BaseUrl, @Resource)", resourceEncodingParameter, baseUrlParameter, resourceParameter);
        }
    
        [DbFunction("BANKSEntities", "GetSOAP")]
        public virtual IQueryable<GetSOAP_Result> GetSOAP(string resourceEncoding, string url, string contentType, string method, string soapEnvelope)
        {
            var resourceEncodingParameter = resourceEncoding != null ?
                new ObjectParameter("ResourceEncoding", resourceEncoding) :
                new ObjectParameter("ResourceEncoding", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            var contentTypeParameter = contentType != null ?
                new ObjectParameter("ContentType", contentType) :
                new ObjectParameter("ContentType", typeof(string));
    
            var methodParameter = method != null ?
                new ObjectParameter("method", method) :
                new ObjectParameter("method", typeof(string));
    
            var soapEnvelopeParameter = soapEnvelope != null ?
                new ObjectParameter("soapEnvelope", soapEnvelope) :
                new ObjectParameter("soapEnvelope", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetSOAP_Result>("[BANKSEntities].[GetSOAP](@ResourceEncoding, @url, @ContentType, @method, @soapEnvelope)", resourceEncodingParameter, urlParameter, contentTypeParameter, methodParameter, soapEnvelopeParameter);
        }
    
        public virtual int p_BIC_CO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_BIC_CO");
        }
    
        public virtual int p_BicToIntCode()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_BicToIntCode");
        }
    
        public virtual int p_BicToRegNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_BicToRegNumber");
        }
    
        public virtual int p_Data101(string indCode, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var indCodeParameter = indCode != null ?
                new ObjectParameter("IndCode", indCode) :
                new ObjectParameter("IndCode", typeof(string));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data101", indCodeParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual int p_Data101_cursor_by_IndCode(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data101_cursor_by_IndCode", dateFromParameter, dateToParameter);
        }
    
        public virtual int p_Form101Indicators()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Form101Indicators");
        }
    
        public virtual int p_launcher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_launcher");
        }
    
        [DbFunction("BANKSEntities", "f_application_F101_actives_top_n")]
        public virtual IQueryable<f_application_F101_actives_top_n_Result> f_application_F101_actives_top_n(Nullable<System.DateTime> dt_slice, Nullable<System.DateTime> dt_from, Nullable<int> top_n)
        {
            var dt_sliceParameter = dt_slice.HasValue ?
                new ObjectParameter("dt_slice", dt_slice) :
                new ObjectParameter("dt_slice", typeof(System.DateTime));
    
            var dt_fromParameter = dt_from.HasValue ?
                new ObjectParameter("dt_from", dt_from) :
                new ObjectParameter("dt_from", typeof(System.DateTime));
    
            var top_nParameter = top_n.HasValue ?
                new ObjectParameter("top_n", top_n) :
                new ObjectParameter("top_n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_application_F101_actives_top_n_Result>("[BANKSEntities].[f_application_F101_actives_top_n](@dt_slice, @dt_from, @top_n)", dt_sliceParameter, dt_fromParameter, top_nParameter);
        }
    
        public virtual int p_application_datasets()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_application_datasets");
        }
    
        public virtual ObjectResult<p1_Result> p1(Nullable<System.DateTime> dt_slice, Nullable<System.DateTime> dt_from, Nullable<int> top_n)
        {
            var dt_sliceParameter = dt_slice.HasValue ?
                new ObjectParameter("dt_slice", dt_slice) :
                new ObjectParameter("dt_slice", typeof(System.DateTime));
    
            var dt_fromParameter = dt_from.HasValue ?
                new ObjectParameter("dt_from", dt_from) :
                new ObjectParameter("dt_from", typeof(System.DateTime));
    
            var top_nParameter = top_n.HasValue ?
                new ObjectParameter("top_n", top_n) :
                new ObjectParameter("top_n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p1_Result>("p1", dt_sliceParameter, dt_fromParameter, top_nParameter);
        }
    
        public virtual ObjectResult<p_application_dataset_F101_actives_top_n_Result> p_application_dataset_F101_actives_top_n(Nullable<System.DateTime> dt_slice, Nullable<System.DateTime> dt_from, Nullable<int> top_n)
        {
            var dt_sliceParameter = dt_slice.HasValue ?
                new ObjectParameter("dt_slice", dt_slice) :
                new ObjectParameter("dt_slice", typeof(System.DateTime));
    
            var dt_fromParameter = dt_from.HasValue ?
                new ObjectParameter("dt_from", dt_from) :
                new ObjectParameter("dt_from", typeof(System.DateTime));
    
            var top_nParameter = top_n.HasValue ?
                new ObjectParameter("top_n", top_n) :
                new ObjectParameter("top_n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_application_dataset_F101_actives_top_n_Result>("p_application_dataset_F101_actives_top_n", dt_sliceParameter, dt_fromParameter, top_nParameter);
        }
    
        public virtual int p_application_datasets_static()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_application_datasets_static");
        }
    
        public virtual ObjectResult<p_application_dataset_F101_passives_top_n_Result> p_application_dataset_F101_passives_top_n(Nullable<System.DateTime> dt_slice, Nullable<System.DateTime> dt_from, Nullable<int> top_n)
        {
            var dt_sliceParameter = dt_slice.HasValue ?
                new ObjectParameter("dt_slice", dt_slice) :
                new ObjectParameter("dt_slice", typeof(System.DateTime));
    
            var dt_fromParameter = dt_from.HasValue ?
                new ObjectParameter("dt_from", dt_from) :
                new ObjectParameter("dt_from", typeof(System.DateTime));
    
            var top_nParameter = top_n.HasValue ?
                new ObjectParameter("top_n", top_n) :
                new ObjectParameter("top_n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_application_dataset_F101_passives_top_n_Result>("p_application_dataset_F101_passives_top_n", dt_sliceParameter, dt_fromParameter, top_nParameter);
        }
    
        public virtual ObjectResult<p_application_dataset_F101_Result> p_application_dataset_F101(string mODE, Nullable<int> tip, string str, string dt_from, string dt_to)
        {
            var mODEParameter = mODE != null ?
                new ObjectParameter("MODE", mODE) :
                new ObjectParameter("MODE", typeof(string));
    
            var tipParameter = tip.HasValue ?
                new ObjectParameter("tip", tip) :
                new ObjectParameter("tip", typeof(int));
    
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));
    
            var dt_fromParameter = dt_from != null ?
                new ObjectParameter("dt_from", dt_from) :
                new ObjectParameter("dt_from", typeof(string));
    
            var dt_toParameter = dt_to != null ?
                new ObjectParameter("dt_to", dt_to) :
                new ObjectParameter("dt_to", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_application_dataset_F101_Result>("p_application_dataset_F101", mODEParameter, tipParameter, strParameter, dt_fromParameter, dt_toParameter);
        }
    
        public virtual ObjectResult<p_application_bankinfo_Result> p_application_bankinfo(string mODE, string shortname, Nullable<int> n)
        {
            var mODEParameter = mODE != null ?
                new ObjectParameter("MODE", mODE) :
                new ObjectParameter("MODE", typeof(string));
    
            var shortnameParameter = shortname != null ?
                new ObjectParameter("shortname", shortname) :
                new ObjectParameter("shortname", typeof(string));
    
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_application_bankinfo_Result>("p_application_bankinfo", mODEParameter, shortnameParameter, nParameter);
        }
    
        public virtual ObjectResult<p_application_dates_Result> p_application_dates(string obj)
        {
            var objParameter = obj != null ?
                new ObjectParameter("obj", obj) :
                new ObjectParameter("obj", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_application_dates_Result>("p_application_dates", objParameter);
        }
    
        public virtual ObjectResult<p_application_dataset_F102_Result> p_application_dataset_F102(string slice, Nullable<int> field_id, string regn, string dt_from, string dt_to)
        {
            var sliceParameter = slice != null ?
                new ObjectParameter("slice", slice) :
                new ObjectParameter("slice", typeof(string));
    
            var field_idParameter = field_id.HasValue ?
                new ObjectParameter("Field_id", field_id) :
                new ObjectParameter("Field_id", typeof(int));
    
            var regnParameter = regn != null ?
                new ObjectParameter("regn", regn) :
                new ObjectParameter("regn", typeof(string));
    
            var dt_fromParameter = dt_from != null ?
                new ObjectParameter("dt_from", dt_from) :
                new ObjectParameter("dt_from", typeof(string));
    
            var dt_toParameter = dt_to != null ?
                new ObjectParameter("dt_to", dt_to) :
                new ObjectParameter("dt_to", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_application_dataset_F102_Result>("p_application_dataset_F102", sliceParameter, field_idParameter, regnParameter, dt_fromParameter, dt_toParameter);
        }
    }
}
