//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Form101Indicators
    {
        public int IndID { get; set; }
        public string IndCode { get; set; }
        public string Name { get; set; }
        public Nullable<int> IndType { get; set; }
        public string IndChapter { get; set; }
        public Nullable<System.DateTime> LOAD_DT { get; set; }
    }
}
