//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Form102Indicators_flat
    {
        public Nullable<int> symid { get; set; }
        public Nullable<int> symsort { get; set; }
        public string name { get; set; }
        public int symbol { get; set; }
        public Nullable<int> symtype { get; set; }
        public Nullable<int> symset { get; set; }
        public Nullable<System.DateTime> LOAD_DT { get; set; }
        public string Part { get; set; }
        public string Section { get; set; }
        public string Article { get; set; }
        public string Part_name { get; set; }
        public string Section_name { get; set; }
        public string Article_name { get; set; }
        public Nullable<int> Part_id { get; set; }
        public Nullable<int> Section_id { get; set; }
        public Nullable<int> Article_id { get; set; }
    }
}
